#!/usr/bin/env node
/**
 * Generiert aus tokens.json + presets/*.json folgende CSS-Dateien in dist/:
 *   primitives.css        — :root { --color-n-900: ...; ... }
 *   preset-dark.css       — [data-theme="dark"] { --bg: ...; ... }
 *   preset-light.css      — [data-theme="light"] { ... }
 *   preset-terminal.css   — [data-theme="terminal"] { ... }
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dir = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dir, "..");
const distDir = resolve(root, "dist");

mkdirSync(distDir, { recursive: true });

const tokens = JSON.parse(readFileSync(resolve(root, "tokens.json"), "utf8"));

// ── 1. primitives.css ──────────────────────────────────────────────────────

function flattenTokens(obj, prefix = "--") {
  const vars = [];
  for (const [key, val] of Object.entries(obj)) {
    const sep = prefix === "--" ? "" : "-";
  const cssKey = `${prefix}${sep}${key}`;
    if (typeof val === "object" && val !== null) {
      vars.push(...flattenTokens(val, cssKey));
    } else {
      vars.push(`  ${cssKey}: ${val};`);
    }
  }
  return vars;
}

const primitiveLines = [
  "/* Auto-generated by build-css.mjs — do not edit */",
  ":root {",
  ...flattenTokens(tokens),
  "}",
  "",
];

writeFileSync(resolve(distDir, "primitives.css"), primitiveLines.join("\n"), "utf8");
console.log("✓  dist/primitives.css");

// ── 2. preset-*.css ────────────────────────────────────────────────────────

const presetFiles = ["itsweber-dark", "itsweber-light", "itsweber-terminal"];

for (const name of presetFiles) {
  const preset = JSON.parse(
    readFileSync(resolve(root, "presets", `${name}.json`), "utf8")
  );

  const selector = `[data-theme="${preset.dataTheme}"]`;
  const lines = [
    `/* Auto-generated — ${preset.label} */`,
    `${selector} {`,
    ...Object.entries(preset.vars).map(([k, v]) => `  ${k}: ${v};`),
    "}",
    "",
  ];

  const outName = `preset-${preset.dataTheme}.css`;
  writeFileSync(resolve(distDir, outName), lines.join("\n"), "utf8");
  console.log(`✓  dist/${outName}`);
}

console.log("\nTheme build complete.");
