const CDN = "https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg";
const CDN2 = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@main/svg";

export type ServiceCatalogEntry = {
  id: string;
  name: string;
  category: "infrastructure" | "media" | "smart-home" | "tools" | "external";
  iconUrl: string;
  color: string;
};

export function catalogIconUrl(slug: string): string {
  return `${CDN}/${slug}.svg`;
}

function cdn2(slug: string): string {
  return `${CDN2}/${slug}.svg`;
}

function raw(repo: string, path: string): string {
  return `https://raw.githubusercontent.com/${repo}/main/${path}`;
}

export const SERVICE_CATALOG: ServiceCatalogEntry[] = [
  // ── Infrastructure ───────────────────────────────────────────────────────
  { id: "unraid",              name: "Unraid",                 category: "infrastructure", iconUrl: catalogIconUrl("unraid"),                color: "#f97316" },
  { id: "proxmox",             name: "Proxmox",                category: "infrastructure", iconUrl: catalogIconUrl("proxmox"),               color: "#e57000" },
  { id: "truenas",             name: "TrueNAS",                category: "infrastructure", iconUrl: catalogIconUrl("truenas"),               color: "#0095d5" },
  { id: "truenas-scale",       name: "TrueNAS SCALE",          category: "infrastructure", iconUrl: catalogIconUrl("truenas-scale"),         color: "#0095d5" },
  { id: "opnsense",            name: "OPNsense",               category: "infrastructure", iconUrl: catalogIconUrl("opnsense"),              color: "#d94f00" },
  { id: "pfsense",             name: "pfSense",                category: "infrastructure", iconUrl: catalogIconUrl("pfsense"),               color: "#212121" },
  { id: "portainer",           name: "Portainer",              category: "infrastructure", iconUrl: catalogIconUrl("portainer"),             color: "#13bef9" },
  { id: "nginx-proxy-manager", name: "Nginx Proxy Manager",    category: "infrastructure", iconUrl: catalogIconUrl("nginx-proxy-manager"),   color: "#f05a28" },
  { id: "traefik",             name: "Traefik",                category: "infrastructure", iconUrl: catalogIconUrl("traefik"),               color: "#24a1c1" },
  { id: "caddy",               name: "Caddy",                  category: "infrastructure", iconUrl: catalogIconUrl("caddy"),                 color: "#00adef" },
  { id: "haproxy",             name: "HAProxy",                category: "infrastructure", iconUrl: catalogIconUrl("haproxy"),               color: "#1c6eb4" },
  { id: "glances",             name: "Glances",                category: "infrastructure", iconUrl: catalogIconUrl("glances"),               color: "#00d2ff" },
  { id: "netdata",             name: "Netdata",                category: "infrastructure", iconUrl: catalogIconUrl("netdata"),               color: "#00ab44" },
  { id: "grafana",             name: "Grafana",                category: "infrastructure", iconUrl: catalogIconUrl("grafana"),               color: "#f46800" },
  { id: "uptime-kuma",         name: "Uptime Kuma",            category: "infrastructure", iconUrl: catalogIconUrl("uptime-kuma"),           color: "#5cdd8b" },
  { id: "influxdb",            name: "InfluxDB",               category: "infrastructure", iconUrl: catalogIconUrl("influxdb"),              color: "#22adf6" },
  { id: "prometheus",          name: "Prometheus",             category: "infrastructure", iconUrl: catalogIconUrl("prometheus"),            color: "#e6522c" },
  { id: "loki",                name: "Grafana Loki",           category: "infrastructure", iconUrl: catalogIconUrl("grafana"),               color: "#f46800" },
  { id: "docker",              name: "Docker",                 category: "infrastructure", iconUrl: catalogIconUrl("docker"),                color: "#2496ed" },
  { id: "docker-compose",      name: "Docker Compose",         category: "infrastructure", iconUrl: catalogIconUrl("docker"),                color: "#2496ed" },
  { id: "gitea",               name: "Gitea",                  category: "infrastructure", iconUrl: catalogIconUrl("gitea"),                 color: "#609926" },
  { id: "gitlab",              name: "GitLab",                 category: "infrastructure", iconUrl: catalogIconUrl("gitlab"),                color: "#fc6d26" },
  { id: "forgejo",             name: "Forgejo",                category: "infrastructure", iconUrl: catalogIconUrl("forgejo"),               color: "#fb923c" },
  { id: "adguard-home",        name: "AdGuard Home",           category: "infrastructure", iconUrl: catalogIconUrl("adguard-home"),          color: "#68bc71" },
  { id: "pi-hole",             name: "Pi-hole",                category: "infrastructure", iconUrl: catalogIconUrl("pi-hole"),               color: "#f60d1a" },
  { id: "unifi",               name: "UniFi",                  category: "infrastructure", iconUrl: raw("loganmarchione/homelab-svg-assets", "assets/ubiquiti.svg"), color: "#0559c9" },
  { id: "unifi-protect",       name: "UniFi Protect",          category: "infrastructure", iconUrl: cdn2("unifi-protect"),                  color: "#0559c9" },
  { id: "wireguard",           name: "WireGuard",              category: "infrastructure", iconUrl: catalogIconUrl("wireguard"),             color: "#88171a" },
  { id: "tailscale",           name: "Tailscale",              category: "infrastructure", iconUrl: catalogIconUrl("tailscale"),             color: "#246c74" },
  { id: "zerotier",            name: "ZeroTier",               category: "infrastructure", iconUrl: catalogIconUrl("zerotier"),              color: "#ffd700" },
  { id: "cloudflare",          name: "Cloudflare",             category: "infrastructure", iconUrl: catalogIconUrl("cloudflare"),            color: "#f38020" },
  { id: "cloudflare-tunnel",   name: "Cloudflare Tunnel",      category: "infrastructure", iconUrl: catalogIconUrl("cloudflare"),            color: "#f38020" },
  { id: "vaultwarden",         name: "Vaultwarden",            category: "infrastructure", iconUrl: catalogIconUrl("vaultwarden"),           color: "#175ddc" },
  { id: "bitwarden",           name: "Bitwarden",              category: "infrastructure", iconUrl: catalogIconUrl("bitwarden"),             color: "#175ddc" },
  { id: "authentik",           name: "Authentik",              category: "infrastructure", iconUrl: catalogIconUrl("authentik"),             color: "#fd4b2d" },
  { id: "keycloak",            name: "Keycloak",               category: "infrastructure", iconUrl: catalogIconUrl("keycloak"),              color: "#4d9be3" },
  { id: "syncthing",           name: "Syncthing",              category: "infrastructure", iconUrl: catalogIconUrl("syncthing"),             color: "#0891d1" },
  { id: "restic",              name: "Restic",                 category: "infrastructure", iconUrl: catalogIconUrl("restic"),                color: "#f5a623" },
  { id: "duplicati",           name: "Duplicati",              category: "infrastructure", iconUrl: catalogIconUrl("duplicati"),             color: "#1c8a4e" },
  { id: "mariadb",             name: "MariaDB",                category: "infrastructure", iconUrl: catalogIconUrl("mariadb"),               color: "#c0765a" },
  { id: "postgresql",          name: "PostgreSQL",             category: "infrastructure", iconUrl: catalogIconUrl("postgresql"),            color: "#336791" },
  { id: "mongodb",             name: "MongoDB",                category: "infrastructure", iconUrl: catalogIconUrl("mongodb"),               color: "#47a248" },
  { id: "redis",               name: "Redis",                  category: "infrastructure", iconUrl: catalogIconUrl("redis"),                 color: "#dc382d" },
  { id: "mosquitto",           name: "Mosquitto",              category: "infrastructure", iconUrl: catalogIconUrl("mosquitto"),             color: "#3c5280" },
  { id: "rabbitmq",            name: "RabbitMQ",               category: "infrastructure", iconUrl: catalogIconUrl("rabbitmq"),              color: "#ff6600" },
  { id: "minio",               name: "MinIO",                  category: "infrastructure", iconUrl: catalogIconUrl("minio"),                 color: "#c72c48" },
  { id: "vault",               name: "HashiCorp Vault",        category: "infrastructure", iconUrl: catalogIconUrl("vault"),                 color: "#ffec6e" },
  { id: "ansible",             name: "Ansible",                category: "infrastructure", iconUrl: catalogIconUrl("ansible"),               color: "#ee0000" },
  { id: "terraform",           name: "Terraform",              category: "infrastructure", iconUrl: catalogIconUrl("terraform"),             color: "#844fba" },
  { id: "kubernetes",          name: "Kubernetes",             category: "infrastructure", iconUrl: catalogIconUrl("kubernetes"),            color: "#326ce5" },
  { id: "rancher",             name: "Rancher",                category: "infrastructure", iconUrl: catalogIconUrl("rancher"),               color: "#0075a8" },

  // ── Smart Home ───────────────────────────────────────────────────────────
  { id: "home-assistant",      name: "Home Assistant",         category: "smart-home",     iconUrl: catalogIconUrl("home-assistant"),        color: "#18bcf2" },
  { id: "node-red",            name: "Node-RED",               category: "smart-home",     iconUrl: catalogIconUrl("node-red"),              color: "#8f0000" },
  { id: "esphome",             name: "ESPHome",                category: "smart-home",     iconUrl: catalogIconUrl("esphome"),               color: "#000000" },
  { id: "zigbee2mqtt",         name: "Zigbee2MQTT",            category: "smart-home",     iconUrl: catalogIconUrl("zigbee2mqtt"),           color: "#e65100" },
  { id: "zwavejs",             name: "Z-Wave JS UI",           category: "smart-home",     iconUrl: catalogIconUrl("zwave-js-ui"),           color: "#1976d2" },
  { id: "frigate",             name: "Frigate",                category: "smart-home",     iconUrl: catalogIconUrl("frigate"),               color: "#00b4d8" },
  { id: "matter-server",       name: "Matter Server",          category: "smart-home",     iconUrl: catalogIconUrl("home-assistant"),        color: "#18bcf2" },
  { id: "scrypted",            name: "Scrypted",               category: "smart-home",     iconUrl: catalogIconUrl("scrypted"),              color: "#4caf50" },
  { id: "go2rtc",              name: "go2rtc",                 category: "smart-home",     iconUrl: cdn2("go2rtc"),                         color: "#00bcd4" },
  { id: "double-take",         name: "Double Take",            category: "smart-home",     iconUrl: cdn2("double-take"),                    color: "#7c4dff" },
  { id: "openthread",          name: "OpenThread Border Router",category: "smart-home",    iconUrl: catalogIconUrl("home-assistant"),        color: "#18bcf2" },

  // ── Media ────────────────────────────────────────────────────────────────
  { id: "plex",                name: "Plex",                   category: "media",          iconUrl: catalogIconUrl("plex"),                  color: "#e5a00d" },
  { id: "jellyfin",            name: "Jellyfin",               category: "media",          iconUrl: catalogIconUrl("jellyfin"),              color: "#00a4dc" },
  { id: "emby",                name: "Emby",                   category: "media",          iconUrl: catalogIconUrl("emby"),                  color: "#52b54b" },
  { id: "kodi",                name: "Kodi",                   category: "media",          iconUrl: catalogIconUrl("kodi"),                  color: "#17b2e7" },
  { id: "sonarr",              name: "Sonarr",                 category: "media",          iconUrl: catalogIconUrl("sonarr"),                color: "#35c5f4" },
  { id: "radarr",              name: "Radarr",                 category: "media",          iconUrl: catalogIconUrl("radarr"),                color: "#ffc230" },
  { id: "lidarr",              name: "Lidarr",                 category: "media",          iconUrl: catalogIconUrl("lidarr"),                color: "#00c875" },
  { id: "readarr",             name: "Readarr",                category: "media",          iconUrl: catalogIconUrl("readarr"),               color: "#69be28" },
  { id: "whisparr",            name: "Whisparr",               category: "media",          iconUrl: catalogIconUrl("whisparr"),              color: "#ff6b9d" },
  { id: "prowlarr",            name: "Prowlarr",               category: "media",          iconUrl: catalogIconUrl("prowlarr"),              color: "#f36a23" },
  { id: "bazarr",              name: "Bazarr",                 category: "media",          iconUrl: catalogIconUrl("bazarr"),                color: "#dce842" },
  { id: "overseerr",           name: "Overseerr",              category: "media",          iconUrl: catalogIconUrl("overseerr"),             color: "#6366f1" },
  { id: "jellyseerr",          name: "Jellyseerr",             category: "media",          iconUrl: catalogIconUrl("jellyseerr"),            color: "#6366f1" },
  { id: "tautulli",            name: "Tautulli",               category: "media",          iconUrl: catalogIconUrl("tautulli"),              color: "#e5a00d" },
  { id: "audiobookshelf",      name: "Audiobookshelf",         category: "media",          iconUrl: catalogIconUrl("audiobookshelf"),        color: "#c8a55f" },
  { id: "immich",              name: "Immich",                 category: "media",          iconUrl: catalogIconUrl("immich"),                color: "#4250af" },
  { id: "photoprism",          name: "PhotoPrism",             category: "media",          iconUrl: catalogIconUrl("photoprism"),            color: "#7fd3f7" },
  { id: "nextcloud",           name: "Nextcloud",              category: "media",          iconUrl: catalogIconUrl("nextcloud"),             color: "#0082c9" },
  { id: "seafile",             name: "Seafile",                category: "media",          iconUrl: catalogIconUrl("seafile"),               color: "#002e5b" },
  { id: "kavita",              name: "Kavita",                 category: "media",          iconUrl: catalogIconUrl("kavita"),                color: "#444444" },
  { id: "komga",               name: "Komga",                  category: "media",          iconUrl: catalogIconUrl("komga"),                 color: "#4caf50" },
  { id: "calibre",             name: "Calibre",                category: "media",          iconUrl: catalogIconUrl("calibre"),               color: "#634c37" },
  { id: "calibre-web",         name: "Calibre-Web",            category: "media",          iconUrl: catalogIconUrl("calibre-web"),           color: "#634c37" },
  { id: "navidrome",           name: "Navidrome",              category: "media",          iconUrl: catalogIconUrl("navidrome"),             color: "#f0483e" },
  { id: "funkwhale",           name: "Funkwhale",              category: "media",          iconUrl: catalogIconUrl("funkwhale"),             color: "#e67e22" },
  { id: "airsonic",            name: "Airsonic",               category: "media",          iconUrl: cdn2("airsonic"),                       color: "#f5a623" },
  { id: "pinchflat",           name: "Pinchflat",              category: "media",          iconUrl: catalogIconUrl("pinchflat"),             color: "#ff0000" },
  { id: "tubesync",            name: "TubeSync",               category: "media",          iconUrl: cdn2("tubesync"),                       color: "#ff0000" },
  { id: "xteve",               name: "xTeVe",                  category: "media",          iconUrl: cdn2("xteve"),                          color: "#e53935" },
  { id: "channels-dvr",        name: "Channels DVR",           category: "media",          iconUrl: cdn2("channels"),                       color: "#0072c6" },

  // ── Tools ────────────────────────────────────────────────────────────────
  { id: "heimdall",            name: "Heimdall",               category: "tools",          iconUrl: catalogIconUrl("heimdall"),              color: "#413c6d" },
  { id: "homer",               name: "Homer",                  category: "tools",          iconUrl: catalogIconUrl("homer"),                 color: "#4169e1" },
  { id: "dashy",               name: "Dashy",                  category: "tools",          iconUrl: catalogIconUrl("dashy"),                 color: "#00dbe7" },
  { id: "homarr",              name: "Homarr",                 category: "tools",          iconUrl: catalogIconUrl("homarr"),                color: "#fa5252" },
  { id: "scrutiny",            name: "Scrutiny",               category: "tools",          iconUrl: catalogIconUrl("scrutiny"),              color: "#ef5350" },
  { id: "speedtest",           name: "Speedtest Tracker",      category: "tools",          iconUrl: catalogIconUrl("speedtest-tracker"),     color: "#141526" },
  { id: "transmission",        name: "Transmission",           category: "tools",          iconUrl: catalogIconUrl("transmission"),          color: "#c0392b" },
  { id: "qbittorrent",         name: "qBittorrent",            category: "tools",          iconUrl: catalogIconUrl("qbittorrent"),           color: "#1dacf5" },
  { id: "deluge",              name: "Deluge",                 category: "tools",          iconUrl: catalogIconUrl("deluge"),                color: "#649f35" },
  { id: "sabnzbd",             name: "SABnzbd",                category: "tools",          iconUrl: catalogIconUrl("sabnzbd"),               color: "#f5c518" },
  { id: "nzbget",              name: "NZBGet",                 category: "tools",          iconUrl: catalogIconUrl("nzbget"),                color: "#42b649" },
  { id: "jdownloader",         name: "JDownloader",            category: "tools",          iconUrl: cdn2("jdownloader"),                    color: "#f6c90e" },
  { id: "adminer",             name: "Adminer",                category: "tools",          iconUrl: catalogIconUrl("adminer"),               color: "#e74c3c" },
  { id: "pgadmin",             name: "pgAdmin",                category: "tools",          iconUrl: catalogIconUrl("pgadmin"),               color: "#316192" },
  { id: "phpmyadmin",          name: "phpMyAdmin",             category: "tools",          iconUrl: catalogIconUrl("phpmyadmin"),            color: "#f89c0e" },
  { id: "mainsail",            name: "Mainsail",               category: "tools",          iconUrl: catalogIconUrl("mainsail"),              color: "#2196f3" },
  { id: "fluidd",              name: "Fluidd",                 category: "tools",          iconUrl: catalogIconUrl("fluidd"),                color: "#1565c0" },
  { id: "octoprint",           name: "OctoPrint",              category: "tools",          iconUrl: catalogIconUrl("octoprint"),             color: "#13c100" },
  { id: "nginx",               name: "Nginx",                  category: "tools",          iconUrl: catalogIconUrl("nginx"),                 color: "#009900" },
  { id: "apache",              name: "Apache",                 category: "tools",          iconUrl: catalogIconUrl("apache"),                color: "#d22128" },
  { id: "vscode-server",       name: "VS Code Server",         category: "tools",          iconUrl: catalogIconUrl("vscode"),                color: "#007acc" },
  { id: "code-server",         name: "code-server",            category: "tools",          iconUrl: catalogIconUrl("code-server"),           color: "#007acc" },
  { id: "obsidian",            name: "Obsidian",               category: "tools",          iconUrl: catalogIconUrl("obsidian"),              color: "#7c3aed" },
  { id: "joplin",              name: "Joplin",                 category: "tools",          iconUrl: catalogIconUrl("joplin"),                color: "#1071d3" },
  { id: "tandoor",             name: "Tandoor Recipes",        category: "tools",          iconUrl: catalogIconUrl("tandoor"),               color: "#c49400" },
  { id: "mealie",              name: "Mealie",                 category: "tools",          iconUrl: catalogIconUrl("mealie"),                color: "#e8a400" },
  { id: "grocy",               name: "Grocy",                  category: "tools",          iconUrl: catalogIconUrl("grocy"),                 color: "#85c443" },
  { id: "paperless-ngx",       name: "Paperless-ngx",          category: "tools",          iconUrl: catalogIconUrl("paperless-ngx"),         color: "#17541f" },
  { id: "stirling-pdf",        name: "Stirling PDF",           category: "tools",          iconUrl: catalogIconUrl("stirling-pdf"),          color: "#ef4444" },
  { id: "vikunja",             name: "Vikunja",                category: "tools",          iconUrl: catalogIconUrl("vikunja"),               color: "#4f81e5" },
  { id: "linkwarden",          name: "Linkwarden",             category: "tools",          iconUrl: catalogIconUrl("linkwarden"),            color: "#0284c7" },
  { id: "linkding",            name: "Linkding",               category: "tools",          iconUrl: catalogIconUrl("linkding"),              color: "#3d7fc1" },
  { id: "shlink",              name: "Shlink",                 category: "tools",          iconUrl: catalogIconUrl("shlink"),                color: "#4696e9" },
  { id: "privatebin",          name: "PrivateBin",             category: "tools",          iconUrl: catalogIconUrl("privatebin"),            color: "#606060" },
  { id: "it-tools",            name: "IT Tools",               category: "tools",          iconUrl: catalogIconUrl("it-tools"),              color: "#6366f1" },
  { id: "changedetection",     name: "Changedetection.io",     category: "tools",          iconUrl: catalogIconUrl("changedetection"),       color: "#1a73e8" },
  { id: "gatus",               name: "Gatus",                  category: "tools",          iconUrl: catalogIconUrl("gatus"),                 color: "#45b08c" },
  { id: "ntfy",                name: "ntfy",                   category: "tools",          iconUrl: catalogIconUrl("ntfy"),                  color: "#338574" },
  { id: "gotify",              name: "Gotify",                 category: "tools",          iconUrl: catalogIconUrl("gotify"),                color: "#49b4c0" },
  { id: "upsnap",              name: "UpSnap",                 category: "tools",          iconUrl: catalogIconUrl("upsnap"),                color: "#6366f1" },
  { id: "wakapi",              name: "Wakapi",                 category: "tools",          iconUrl: catalogIconUrl("wakapi"),                color: "#f97316" },
  { id: "actual-budget",       name: "Actual Budget",          category: "tools",          iconUrl: catalogIconUrl("actual"),                color: "#2c7be5" },
  { id: "firefly-iii",         name: "Firefly III",            category: "tools",          iconUrl: catalogIconUrl("firefly-iii"),           color: "#ff6600" },

  // ── Infrastructure (continued) ───────────────────────────────────────────
  { id: "semaphore",            name: "Ansible Semaphore",      category: "infrastructure", iconUrl: catalogIconUrl("semaphore"),             color: "#4da6ff" },
  { id: "netbox",               name: "NetBox",                 category: "infrastructure", iconUrl: catalogIconUrl("netbox"),                color: "#9c27b0" },
  { id: "librenms",             name: "LibreNMS",               category: "infrastructure", iconUrl: catalogIconUrl("librenms"),              color: "#f4a522" },
  { id: "zabbix",               name: "Zabbix",                 category: "infrastructure", iconUrl: catalogIconUrl("zabbix"),                color: "#d62f2f" },
  { id: "checkmk",              name: "Checkmk",                category: "infrastructure", iconUrl: cdn2("checkmk"),                        color: "#15a084" },
  { id: "healthchecks",         name: "Healthchecks.io",        category: "infrastructure", iconUrl: catalogIconUrl("healthchecks"),          color: "#4688e4" },
  { id: "stirling-pdf-2",       name: "Stirling PDF v2",        category: "infrastructure", iconUrl: catalogIconUrl("stirling-pdf"),          color: "#ef4444" },
  { id: "cloudbeaver",          name: "CloudBeaver",            category: "infrastructure", iconUrl: cdn2("dbeaver"),                        color: "#1a74e0" },
  { id: "dozzle",               name: "Dozzle",                 category: "infrastructure", iconUrl: catalogIconUrl("dozzle"),                color: "#f59e0b" },
  { id: "watchtower",           name: "Watchtower",             category: "infrastructure", iconUrl: catalogIconUrl("watchtower"),            color: "#2196f3" },
  { id: "diun",                 name: "Diun",                   category: "infrastructure", iconUrl: cdn2("diun"),                           color: "#5c6bc0" },
  { id: "heimdall-infra",       name: "Heimdall",               category: "infrastructure", iconUrl: catalogIconUrl("heimdall"),              color: "#413c6d" },
  { id: "crowdsec",             name: "CrowdSec",               category: "infrastructure", iconUrl: catalogIconUrl("crowdsec"),              color: "#2e7d32" },
  { id: "fail2ban",             name: "Fail2Ban",               category: "infrastructure", iconUrl: cdn2("fail2ban"),                       color: "#ff5722" },
  { id: "openvpn",              name: "OpenVPN",                category: "infrastructure", iconUrl: catalogIconUrl("openvpn"),               color: "#ea7e20" },
  { id: "headscale",            name: "Headscale",              category: "infrastructure", iconUrl: catalogIconUrl("headscale"),             color: "#246c74" },
  { id: "wg-easy",              name: "wg-easy",                category: "infrastructure", iconUrl: catalogIconUrl("wireguard"),             color: "#88171a" },
  { id: "nginxproxymanager2",   name: "NPM v3",                 category: "infrastructure", iconUrl: catalogIconUrl("nginx-proxy-manager"),   color: "#f05a28" },
  { id: "certbot",              name: "Certbot",                category: "infrastructure", iconUrl: cdn2("letsencrypt"),                    color: "#003a70" },
  { id: "step-ca",              name: "Step CA",                category: "infrastructure", iconUrl: cdn2("step-ca"),                        color: "#00bcd4" },
  { id: "elasticsearch",        name: "Elasticsearch",          category: "infrastructure", iconUrl: catalogIconUrl("elasticsearch"),         color: "#f04e98" },
  { id: "opensearch",           name: "OpenSearch",             category: "infrastructure", iconUrl: catalogIconUrl("opensearch"),            color: "#005eb8" },
  { id: "clickhouse",           name: "ClickHouse",             category: "infrastructure", iconUrl: catalogIconUrl("clickhouse"),            color: "#ffcc01" },
  { id: "nats",                 name: "NATS",                   category: "infrastructure", iconUrl: catalogIconUrl("nats"),                  color: "#27aae1" },
  { id: "kafka",                name: "Apache Kafka",           category: "infrastructure", iconUrl: catalogIconUrl("kafka"),                 color: "#231f20" },
  { id: "n8n",                  name: "n8n",                    category: "infrastructure", iconUrl: catalogIconUrl("n8n"),                   color: "#ea4b71" },

  // ── Smart Home (continued) ───────────────────────────────────────────────
  { id: "homebridge",           name: "Homebridge",             category: "smart-home",     iconUrl: catalogIconUrl("homebridge"),            color: "#491f59" },
  { id: "openhab",              name: "openHAB",                category: "smart-home",     iconUrl: catalogIconUrl("openhab"),               color: "#62ad2c" },
  { id: "domoticz",             name: "Domoticz",               category: "smart-home",     iconUrl: catalogIconUrl("domoticz"),              color: "#95b734" },
  { id: "gladys",               name: "Gladys Assistant",       category: "smart-home",     iconUrl: cdn2("gladys"),                         color: "#2e86de" },
  { id: "ring",                 name: "Ring",                   category: "smart-home",     iconUrl: catalogIconUrl("ring"),                  color: "#1c9be6" },
  { id: "wyze",                 name: "Wyze",                   category: "smart-home",     iconUrl: cdn2("wyze"),                           color: "#0068ff" },
  { id: "alarmdotcom",          name: "Alarm.com",              category: "smart-home",     iconUrl: cdn2("alarm"),                          color: "#d62d20" },
  { id: "loxone",               name: "Loxone",                 category: "smart-home",     iconUrl: catalogIconUrl("loxone"),                color: "#69a132" },

  // ── Media (continued) ────────────────────────────────────────────────────
  { id: "stash",                name: "Stash",                  category: "media",          iconUrl: catalogIconUrl("stash"),                 color: "#c31b76" },
  { id: "mylar",                name: "Mylar3",                 category: "media",          iconUrl: catalogIconUrl("mylar"),                 color: "#3498db" },
  { id: "lazylibrarian",        name: "LazyLibrarian",          category: "media",          iconUrl: cdn2("lazylibrarian"),                  color: "#95a5a6" },
  { id: "metube",               name: "MeTube",                 category: "media",          iconUrl: catalogIconUrl("metube"),                color: "#ff0000" },
  { id: "tubearchivist",        name: "TubeArchivist",          category: "media",          iconUrl: catalogIconUrl("tubearchivist"),         color: "#ff2d55" },
  { id: "peerflix",             name: "Peerflix",               category: "media",          iconUrl: cdn2("peerflix"),                       color: "#1db954" },
  { id: "stremio",              name: "Stremio",                category: "media",          iconUrl: catalogIconUrl("stremio"),               color: "#7b5ea7" },
  { id: "photoview",            name: "Photoview",              category: "media",          iconUrl: catalogIconUrl("photoview"),             color: "#6c63ff" },
  { id: "lychee",               name: "Lychee",                 category: "media",          iconUrl: catalogIconUrl("lychee"),                color: "#ff6b6b" },
  { id: "piwigo",               name: "Piwigo",                 category: "media",          iconUrl: catalogIconUrl("piwigo"),                color: "#ff7700" },
  { id: "subsonic",             name: "Subsonic",               category: "media",          iconUrl: cdn2("subsonic"),                       color: "#03a9f4" },

  // ── Tools (continued) ────────────────────────────────────────────────────
  { id: "bookstack",            name: "BookStack",              category: "tools",          iconUrl: catalogIconUrl("bookstack"),             color: "#0288d1" },
  { id: "wiki-js",              name: "Wiki.js",                category: "tools",          iconUrl: catalogIconUrl("wiki-js"),               color: "#1976d2" },
  { id: "outline",              name: "Outline",                category: "tools",          iconUrl: catalogIconUrl("outline"),               color: "#000000" },
  { id: "docuseal",             name: "DocuSeal",               category: "tools",          iconUrl: cdn2("docuseal"),                       color: "#2563eb" },
  { id: "mattermost",           name: "Mattermost",             category: "tools",          iconUrl: catalogIconUrl("mattermost"),            color: "#0058cc" },
  { id: "rocketchat",           name: "Rocket.Chat",            category: "tools",          iconUrl: catalogIconUrl("rocketchat"),            color: "#e01e3c" },
  { id: "matrix-synapse",       name: "Matrix Synapse",         category: "tools",          iconUrl: catalogIconUrl("matrix"),               color: "#0dbd8b" },
  { id: "element",              name: "Element",                category: "tools",          iconUrl: catalogIconUrl("element"),               color: "#0dbd8b" },
  { id: "excalidraw",           name: "Excalidraw",             category: "tools",          iconUrl: catalogIconUrl("excalidraw"),            color: "#6965db" },
  { id: "hedgedoc",             name: "HedgeDoc",               category: "tools",          iconUrl: catalogIconUrl("hedgedoc"),              color: "#b51f08" },
  { id: "codimd",               name: "CodiMD",                 category: "tools",          iconUrl: cdn2("codimd"),                         color: "#b51f08" },
  { id: "cryptpad",             name: "CryptPad",               category: "tools",          iconUrl: catalogIconUrl("cryptpad"),              color: "#ce0000" },
  { id: "answer",               name: "Answer",                 category: "tools",          iconUrl: cdn2("answer"),                         color: "#0052cc" },
  { id: "glitchtip",            name: "GlitchTip",              category: "tools",          iconUrl: cdn2("glitchtip"),                      color: "#e8304b" },
  { id: "woodpecker",           name: "Woodpecker CI",          category: "tools",          iconUrl: catalogIconUrl("woodpecker"),            color: "#09b552" },
  { id: "drone",                name: "Drone CI",               category: "tools",          iconUrl: catalogIconUrl("drone"),                 color: "#212121" },
  { id: "jenkins",              name: "Jenkins",                category: "tools",          iconUrl: catalogIconUrl("jenkins"),               color: "#d33833" },
  { id: "gitlab-runner",        name: "GitLab Runner",          category: "tools",          iconUrl: catalogIconUrl("gitlab"),               color: "#fc6d26" },
  { id: "sentry",               name: "Sentry",                 category: "tools",          iconUrl: catalogIconUrl("sentry"),                color: "#362d59" },
  { id: "posthog",              name: "PostHog",                category: "tools",          iconUrl: catalogIconUrl("posthog"),               color: "#f54e00" },
  { id: "plausible",            name: "Plausible",              category: "tools",          iconUrl: catalogIconUrl("plausible"),             color: "#5850ec" },
  { id: "umami",                name: "Umami",                  category: "tools",          iconUrl: catalogIconUrl("umami"),                 color: "#6967d6" },
  { id: "matomo",               name: "Matomo",                 category: "tools",          iconUrl: catalogIconUrl("matomo"),                color: "#3152a0" },

  // ── External ─────────────────────────────────────────────────────────────
  { id: "github",              name: "GitHub",                 category: "external",       iconUrl: catalogIconUrl("github"),                color: "#24292e" },
  { id: "cloudflare-ext",      name: "Cloudflare",             category: "external",       iconUrl: catalogIconUrl("cloudflare"),            color: "#f38020" },
  { id: "google",              name: "Google",                 category: "external",       iconUrl: catalogIconUrl("google"),                color: "#4285f4" },
  { id: "google-drive",        name: "Google Drive",           category: "external",       iconUrl: catalogIconUrl("google-drive"),          color: "#0f9d58" },
  { id: "gmail",               name: "Gmail",                  category: "external",       iconUrl: catalogIconUrl("gmail"),                 color: "#ea4335" },
  { id: "youtube",             name: "YouTube",                category: "external",       iconUrl: catalogIconUrl("youtube"),               color: "#ff0000" },
  { id: "twitter-x",           name: "X (Twitter)",            category: "external",       iconUrl: catalogIconUrl("x"),                     color: "#000000" },
  { id: "reddit",              name: "Reddit",                 category: "external",       iconUrl: catalogIconUrl("reddit"),                color: "#ff4500" },
  { id: "discord",             name: "Discord",                category: "external",       iconUrl: catalogIconUrl("discord"),               color: "#5865f2" },
  { id: "slack",               name: "Slack",                  category: "external",       iconUrl: catalogIconUrl("slack"),                 color: "#4a154b" },
  { id: "telegram",            name: "Telegram",               category: "external",       iconUrl: catalogIconUrl("telegram"),              color: "#26a5e4" },
  { id: "whatsapp",            name: "WhatsApp",               category: "external",       iconUrl: catalogIconUrl("whatsapp"),              color: "#25d366" },
  { id: "amazon",              name: "Amazon",                 category: "external",       iconUrl: catalogIconUrl("amazon"),                color: "#ff9900" },
  { id: "netflix",             name: "Netflix",                category: "external",       iconUrl: catalogIconUrl("netflix"),               color: "#e50914" },
  { id: "spotify",             name: "Spotify",                category: "external",       iconUrl: catalogIconUrl("spotify"),               color: "#1db954" },
  { id: "openai",              name: "OpenAI / ChatGPT",        category: "external",       iconUrl: catalogIconUrl("openai"),                color: "#412991" },
];

export const CATALOG_BY_ID = new Map(SERVICE_CATALOG.map((e) => [e.id, e]));
